name: Build and Deploy

on: push

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Make bin folder
        run: mkdir -p $HOME/bin
      - name: Install Hugo
        run: ./ci-install-hugo.sh
        env:
          HUGO_VERSION: 0.58.2
      - name: Hugo Build
        run: $HOME/bin/hugo -v
      - name: Deploy to S3
        # if: github.ref == 'refs/heads/master'
        run: $HOME/bin/hugo -v deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
